### ISSUE TITLE
NameSpaceProblem

### ISSUE THREAD

**Issue by chriza** [agoat/contao-contentblocks-bundle#1]
Hallo,
habe Contao 4.2 installiert und habe die ContentBlocks installiert.
php composer require agoat/contentblocks-bundle
AppKernel.php: new Agoat\ContentBlocksBundle\AgoatContentBlocksBundle(),
## Beim Clearen den Cache erhalte ich folgende Meldung:

php app/console cache:clear --env=prod --no-debug

 // Clearing the cache for the prod environment with debug false

PHP Fatal error:  Cannot declare class Agoat\ContentBlocks\Controller because the name is already in use in /www/htdocs/w0145fb8/webpages/contao4/bs2016/vendor/agoat/contentblocks-bundle/src/Resources/contao/classes/Controller.php on line 23

Fatal error: Cannot declare class Agoat\ContentBlocks\Controller because the name is already in use in /www/htdocs/w0145fb8/webpages/contao4/bs2016/vendor/agoat/contentblocks-bundle/src/Resources/contao/classes/Controller.php on line 23

  [Symfony\Component\Debug\Exception\FatalErrorException]
##   Compile Error: Cannot declare class Agoat\ContentBlocks\Controller because the name is already in use

Habe ich etwas falsch gemacht, oder liegt ein Fehler vor?

**Comment by agoat** [comment]
Ich hab gerade zum Test eine neue Contao 4.2 Installation mit der ContentBlocks Erweiterung durchgeführt.

```
composer create-project contao/standard-edition contao4-test
cd contao4-test
composer require agoat/contentblocks-bundle
```

Dann die AppKernel.php ergänzt

```
    public function registerBundles()
    {
        $bundles = [
            new Symfony\Bundle\FrameworkBundle\FrameworkBundle(),
            new Symfony\Bundle\SecurityBundle\SecurityBundle(),
            new Symfony\Bundle\TwigBundle\TwigBundle(),
            new Symfony\Bundle\MonologBundle\MonologBundle(),
            new Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle(),
            new Doctrine\Bundle\DoctrineBundle\DoctrineBundle(),
            new Doctrine\Bundle\DoctrineCacheBundle\DoctrineCacheBundle(),
            new Knp\Bundle\TimeBundle\KnpTimeBundle(),
            new Lexik\Bundle\MaintenanceBundle\LexikMaintenanceBundle(),
            new Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle(),
            new Contao\CoreBundle\ContaoCoreBundle(),
            new Contao\CalendarBundle\ContaoCalendarBundle(),
            new Contao\CommentsBundle\ContaoCommentsBundle(),
            new Contao\FaqBundle\ContaoFaqBundle(),
            new Contao\InstallationBundle\ContaoInstallationBundle(),
            new Contao\ListingBundle\ContaoListingBundle(),
            new Contao\NewsBundle\ContaoNewsBundle(),
            new Contao\NewsletterBundle\ContaoNewsletterBundle(),

            new Agoat\ContentBlocksBundle\AgoatContentBlocksBundle()
        ];

        if (in_array($this->getEnvironment(), ['dev', 'test'])) {
            $bundles[] = new Symfony\Bundle\DebugBundle\DebugBundle();
            $bundles[] = new Symfony\Bundle\WebProfilerBundle\WebProfilerBundle();
            $bundles[] = new Sensio\Bundle\DistributionBundle\SensioDistributionBundle();
        }

        return $bundles;
    }
```

Dann nochmal den Cache neu aufgebaut

```
php app/console cache:clear
php app/console cache:clear -e prod
```

Alles ohne einen Fehler. Daher kann ich den Fehler nicht nachvollziehen.

Noch als Hinweis: Ich arbeite mit PHP7 auf meinem Server. Mit PHP5 hab ich das nicht getestet, sollte aber keinen Unterschied machen.

**Comment by chriza** [comment]
Hallo,
ich arbeite mit PHP 5.6.

Habe eine Neuinstallation gemacht und das ContentBlocksBundle als erstes installiert - geht ohne Fehler.
Hatte vorher folgende Extensions installiert: 
1. OneupSecurityCheckerBundle
2. easy_themes
3. notification_center
4. leads
5. boxes4ward
6. CodefogContaoBoostrapBundle

In der neuen Installation erhalte ich noch folgende Warnung:
Warning: Ambiguous class resolution, "Contao\FileTree" was found in both "/www/htdocs/w0145fb8/webpages/contao4/bs2016/vendor/agoat/contentblocks-bundle/src/Resources/contao/widgets/FileTree.php" and "/www/htdocs/w0145fb8/webpages/contao4/bs2016/vendor/contao/core-bundle/src/Resources/contao/widgets/FileTree.php", the first will be used.

**Comment by agoat** [comment]
Die letzte Meldung ist normal, da die FileTree-Klasse überschrieben wird.
