### ISSUE TITLE
Attempted to load class "tl_news_contentblocks" from the global namespace.

### ISSUE THREAD

**Issue by filipbasara** [agoat/contao-contentblocks-bundle#174]
contao-customcontentelements causes the backend to throw an error once I try to duplicate or remove a news post.

More info:
https://community.contao.org/de/showthread.php?71110-4-5-6-Attempted-to-load-class-quot-tl_news_contentblocks-quot-from-the-global-namespace&p=475842#post475842

**Comment by agoat** [comment]
Which version do you use?
Is it a clean installation with the contao manager?

**Comment by filipbasara** [comment]
Sorry I didn't reply earlier. Tried replicating it in a clean contao installation. No luck. However, it seemed to be resolved now and I'm unable to point out what could've "fixed" it. Issue can be closed. Thanks!

**Comment by agoat** [comment]
I think that this bug has already been fixed in a74d880d74352d2ed887e13f29115bbc48ad84cc, which is included in the latest version of April.
