### ISSUE TITLE
(solved) Can't see content element

### ISSUE THREAD

**Issue by JLBA** [agoat/contao-contentblocks-bundle#175]
Hello,
Given a fresh install of Contao 4.4 on MAMP with a contao-customcontentelement installed with contao-manager. I find CCE in Theme. 
I created one new CCE with just two text fields. 
But when adding new content element in article, I don't see my new cce in element type.

Thanks for your help.

**Comment by agoat** [comment]
Have you created only a CCE? If so the CCE should shown at the top of the element type list.
Try to add a category before the CCE and look then for the category name in the list.

**Comment by JLBA** [comment]
Thanks Arne .
So now : the CCE is right in the Element type menu, I can add it in an article and fill in the fields.
But : 
- in the BE : I can #see the CE but not its content ; 
- in the FE : I see a back link (which doesn't work) and nothing. 

Here is the code I find :           
```
<div id="article-3" class="mod-article first last block">
    <h1 class="ce_headline first">Bienvenue</h1>
    <div class="contentblock">
      <!-- headline (textfield) -->
<div class="headline"></div>
     <!-- text (textarea) -->
     <div class="text">
     </div>
    <!-- single images (source selection) -->
    <div class="image">
    </div>
</div>
    <!-- indexer::stop -->
   <p class="back"><a href="javascript:history.go(-1)" title="Retour">Retour</a></p>
   <!-- indexer::continue -->
   <div>
<div>
```
Here are screenhots. 
![screenshot_2019-02-07 articles accueil elements de contenu editer l element de contenu id 13 - contao open source cms](https://user-images.githubusercontent.com/2730432/52437424-2bc3b880-2b17-11e9-9db2-e20a0b11a430.png)          

 ![screenshot_2019-02-07 articles accueil elements de contenu - contao open source cms](https://user-images.githubusercontent.com/2730432/52437423-2bc3b880-2b17-11e9-95d7-043c83a8d1a8.png)

**Comment by agoat** [comment]
It looks like you didn't adjust the CCE template. 

Use the  `ce_standard` template as a start and adjust the outputs (e.g. `<?php echo $this->textfield; ?>`) to what you entered for the field alias (`<?php echo $this->yourFieldAlias; ?>`).

You need a customized template for the CCE to be working. Best is to have a custom template for every CCE.

Yeah, I know it's lacking a decent documentary. After the rollout of my current project, I'm going to get down to it.

**Comment by JLBA** [comment]
Ok. Just have to follow Contao's logical. Thanks.

**Comment by JLBA** [comment]
Is there a way I can help you translate CCE in french ?

**Comment by agoat** [comment]
> Is there a way I can help you translate CCE in french ?

Sure you can. Currently there is only Englisch in the `src/Resources/contao/languages` folder. Fork this repository and put the translations into `filename.fr.xlf`. Then make a push request.

But as I said, I'm currently involved in another big project and will not be able to make any real progress here for the next months.
