### ISSUE TITLE
Fehler bei Installation unter Contao 4.6/4.7

### ISSUE THREAD

**Issue by BugBuster1701** [agoat/contao-contentblocks-bundle#176]
Durch die Angabe:
`"symfony/framework-bundle": "^3.3",`

Contao 4.6 benötig:
`"symfony/framework-bundle": "3.4.* || 4.1.*,`
Derzeit ist bei mir die 4.1 installiert, und downgrade auf 3.4.x wäre ungünstig.

Contao 4.7 kann zusätzlich auch mit der 4.2.* vom framework-bundle.

**Comment by agoat** [comment]
Ich habe das noch nicht mit Contao 4.6 getestet.
Aber sollte keine Problem sein.

**Comment by BugBuster1701** [comment]
Bisher unter Contao 4.6 (+Symfony 4.1) keine Probleme.
Ich teste es noch unter 4.7 + Symfony 4.2

**Comment by agoat** [comment]
Behoben mit [Version 2.4](https://packagist.org/packages/agoat/contao-customcontentelements#2.4.0)
Getestet unter Contao 4.4 lts und Contao 4.8
