### ISSUE TITLE
Noch gepflegt?

### ISSUE THREAD

**Issue by Olli** [agoat/contao-contentblocks-bundle#177]
Hi,
wird die Erweiterung noch gepflegt? Auf Contao 4.8 läuft die nämlich nicht und verhindert auch ein Update. Der Fix von Bugbuster wurde auch nicht eingepflegt ... 6 Monate später.

**Comment by agoat** [comment]
Eigentlich wird sie schon noch gepflegt. Nur bin ich seit über einem Jahr in ein großes Cloud-Projekt eingebunden und komme einfach nicht dazu meine Erweiterungen an die neue Contao-Version anzupassen. Selbst meine eigene HP schafft es nicht aus dem Dev-Status hinaus.

Ich habe aber vor alle Erweiterungen dieses Jahr noch mit der aktuelle Contao-Version kompatibel zu machen..

**Comment by Olli** [comment]
Danke für die Info.

**Comment by agoat** [comment]
Es gibt jetzt ein Update.
