### ISSUE TITLE
BE model not found

### ISSUE THREAD

**Issue by JLBA** [agoat/contao-contentblocks-bundle#178]
Hello,
I've created a CE with a custom model from ce_standard "ce_item_programme". 
In FE, this works well. 
For the BE, I created another model "ce_item_programme_be". I can select it in be template field. But when trying to display the article in BE, I got this error : 
![image](https://user-images.githubusercontent.com/2730432/76571696-61746700-64b8-11ea-82d6-81f0904a1444.png)
What's wrong ? Thanks

**Comment by agoat** [comment]
Looks like a coding error in the template.
